### ISSUE TITLE
blog-card ショートコードがエラー

### ISSUE THREAD

**Issue by roheclassic** [okdyy75/hugo-theme-salt#14]
■ 事象
ローカルビルド時に、blog-card ショートコードを使うページがエラーになります。

- エラー内容
```
Start building sites …
hugo v0.100.2-d25cb2943fd94ecf781412aeff9682d5dc62e284+extended linux/amd64 BuildDate=2022-06-08T10:25:57Z VendorInfo=gohugoio
Error: Error building site: "/xxxx/xxxx/xxxxxxxx.md:xx:xx": failed to render shortcode "blog-card": failed to process shortcode: "/xxxx/xxxx/xxxxxxxx/layouts/shortcodes/blog-card.html:24:25": execute of template failed: template: shortcodes/blog-card.html:24:25: executing "shortcodes/blog-card.html" at <$thumbnail.Err>: nil pointer evaluating resource.Resource.Err
Built in 866 ms
```

■ 環境情報

<details><summary>環境情報</summary><div>

```
$ npm version
{
  npm: '8.6.0',
  node: '17.8.0',
  v8: '9.6.180.15-node.16',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '102',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '3.0.2+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

$ hugo version
hugo v0.100.2-d25cb2943fd94ecf781412aeff9682d5dc62e284+extended linux/amd64 BuildDate=2022-06-08T10:25:57Z VendorInfo=gohugoio
```

**Comment by roheclassic** [comment]
サムネイルが取得できない場合の、サイトのエラーハンドリングに問題があるように見えます。
ご確認をお願いできますでしょうか。

ソース修正して事象回避できたので、のちほどお送りします。

**Comment by okdyy75** [comment]
`resources.GetRemote`についてちょっと動作確認して見たんですが、404の場合`.Err`ではなく`nil`が返ってくるのを踏まえて、こんな感じに修正して見たんですが、どうでしょうか？

[blog-cardショートコード使用時にog:imageのリンク切れが分かるように修正](https://github.com/okdyy75/hugo-theme-salt/commit/8591765a6f6e52138ca782db2f48ad0c58d46684)

https://hugo-theme-salt.okdyy75.com/article/salt/blog-card/

![スクリーンショット 2022-07-01 11 10 46](https://user-images.githubusercontent.com/31526134/176813993-3a53920b-ab20-4e5a-837b-541c968e1e59.png)

**Comment by roheclassic** [comment]
この修正内容で良いと思いました！

>404の場合.Errではなくnilが返ってくるのを踏まえて

このあたり挙動不審ですよね・・。nil判定とかどう書けばいんだ！？とかも悩んだり・・。


ご対応ありがとうございました！

**Comment by okdyy75** [comment]
先ほどmainの方に修正内容を取り込みました！
Hugoのドキュメントがもうちょっと詳しく記載してるとありがたいですね〜

**Comment by roheclassic** [comment]
メインにマージされているのを確認しました。
ありがとうございます。
