### ISSUE TITLE
[改善案] blog-card ショートコードのURL読めないとき、ワーニングを出す

### ISSUE THREAD

**Issue by roheclassic** [okdyy75/hugo-theme-salt#16]
改善案です。

## 変更内容

- 現状
```
{{- with $result := resources.GetRemote $url -}}
    {{- if $result.Err -}}
        {{ $result.Err }}
    {{ else }}
```

- 改善後
```
{{- with $result := resources.GetRemote $url -}}
    {{- with $result.Err -}}
        {{ warnf "%s" . }}
        <p><img alt="Page Not Found" width="200" height="100" /></p>
    {{ else }}
```

※pタグは適当でです。

## コメント

 warnf を使うことでビルド時にコンソール WARN出力されるので、その結果リンク切れにきづきやすくなる

**Comment by okdyy75** [comment]
こんな感じの修正でどうでしょうか？

- [ビルド時にblog-cardショートコード内でエラーが起きていたら、コンソール WARN出力するように修正](https://github.com/okdyy75/hugo-theme-salt/commit/3f00e844bfbd58dae7dee05e4ee92341291bbec2)

**Comment by roheclassic** [comment]
とても良い感じだと思います！コミット確認したらクローズします

**Comment by roheclassic** [comment]
mainにマージされているのを確認しました。
