### ISSUE TITLE
プロフィールのSNSアイコンが正しく表示されない。

### ISSUE THREAD

**Issue by roheclassic** [okdyy75/hugo-theme-salt#9]
プロフィールのSNSアイコンが正しく表示されません。
セットアップ直後で、ローカルで動作確認している段階です。
必要な手順があれば教えてください🙇‍♂️

## 期待：

![image](https://user-images.githubusercontent.com/101216239/173251727-8f5a6c09-e046-46d2-97de-9e7d65856f63.png)

## 実際：

![image](https://user-images.githubusercontent.com/101216239/173251757-b1b6fd0a-a841-4850-b4f9-8229230edc40.png)

## 私の環境情報：

$ hugo version
hugo v0.100.2-d25cb2943fd94ecf781412aeff9682d5dc62e284+extended linux/amd64 BuildDate=2022-06-08T10:25:57Z VendorInfo=gohugoio

$ npm version
{
  'hugo-theme-salt': '1.0.0',
  npm: '8.6.0',
  node: '17.8.0',
  v8: '9.6.180.15-node.16',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '102',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '3.0.2+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

**Comment by okdyy75** [comment]
自分の方で確認した環境は下記のとおりなんですが

hugo version
> hugo v0.100.2+extended darwin/amd64 BuildDate=unknown

node -v
> v14.17.0

npm version
```
{
  'hugo-theme-salt': '1.0.0',
  npm: '6.14.16',
  ares: '1.17.1',
  brotli: '1.0.9',
  cldr: '38.1',
  icu: '68.2',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.0',
  openssl: '1.1.1k',
  tz: '2020d',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.63',
  zlib: '1.2.11'
}
```

下記のポイントを確認してみてください！
- [x] テーマ内（hugo-theme-salt）のconfig.ymlをPJにコピーしている
- [x] テーマ内（hugo-theme-salt）のpackage.jsonをPJにコピーして、`npm install`している

**Comment by roheclassic** [comment]
ありがとうございます！

Zennのガイドの手順は実施しており、
Node_moduleとconfig.ymlも存在します。

head.html 内の、jsやcss のパスが通っていなくて、
ここは本来、相対パスではないのかな？と思っています。（ｘ/css/　○css/）

```
    {{ $style := resources.Get "scss/style.scss" | toCSS | minify | fingerprint }}
    <link rel="stylesheet" href="{{ $style.Permalink }}">
    <link rel="preload" href="/css/vendor/@fortawesome/fontawesome-free/css/all.min.css" as="style">
    <link rel="stylesheet" href="/css/vendor/@fortawesome/fontawesome-free/css/all.min.css" media="print" onload="this.media='all'">
    {{ if .IsPage }}
        <link rel="preload" href="/css/vendor/github-markdown-css/github-markdown.css" as="style">
        <link rel="stylesheet" href="/css/vendor/github-markdown-css/github-markdown.css" media="print" onload="this.media='all'">
```

※当環境ではここを相対パスにすると正しく表示されます

ご確認よろしくお願いいたします。

**Comment by roheclassic** [comment]
okdyy75さんの環境で上手く行くのは、おそらくドメインにサブディレクトリがないからだとおもいます。

（私はgitjabでやっているので、gitjabのURL/＜プロジェクト名＞になります。localhostも同様です）

想像ですが、cssやJsも↓のようにベースのURLが補完されたら良いのかなと思いました！

```
    {{ $style := resources.Get "scss/style.scss" | toCSS | minify | fingerprint }}
    <link rel="stylesheet" href="{{ $style.Permalink }}">
```

**Comment by okdyy75** [comment]
なるほど・・！サブディレクトリの場合を考慮していなかったので、ちょっと修正します！

**Comment by roheclassic** [comment]
その後、模索して、私の場合はこれで解消しました。
`href="{{ .Site.BaseURL }}/css/vendor/@fortawesome/fontawesome-free/css/all.min.css" `

**Comment by okdyy75** [comment]
mainブランチに下記修正を取り込みましたのでPJ配下の`/themes/hugo-theme-salt`のmainブランチを更新してみてください！

- [ドメインがサブディレクトリ形式の場合でもアイコン等が表示されるように修正](https://github.com/okdyy75/hugo-theme-salt/commit/e8bb837c06fcc2708c52e00ac8007ab897a3cad7)

サブディレクトリの場合のサンプルソース
https://github.com/okdyy75/salt-sample

合わせてですが、Hugoのテーマをgit cloneしただけではデプロイがうまく動かないのでsubmodule管理に差し替えて頂けると・・！

```
// PJ直下で
rm -rf themes/hugo-theme-salt
git submodule add https://github.com/okdyy75/hugo-theme-salt.git ./themes/hugo-theme-salt
```

**Comment by roheclassic** [comment]
サブディレクトリありで解消確認しました！
Gitlabのサイトの方も正しく表示できました!

サブモジュール再追加は下記で実施しました！（[参考にしたページ](https://qiita.com/shiba_mitue/items/ab63db107ad1904fdeca)）

```
git rm -f  themes/hugo-theme-salt
rm -rf themes/hugo-theme-salt
rm -rf .git/modules/themes/hugo-theme-salt
git submodule add https://github.com/okdyy75/hugo-theme-salt.git ./themes/hugo-theme-salt
```



ありがとうございました！
